# Generated by Django 5.2.7 on 2026-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_book_hobby_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('propic', models.ImageField(blank=True, default='default_user.png', upload_to='profile_pics/')),
            ],
        ),
    ]
