# Generated by Django 5.2.7 on 2026-06-09 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.SlugField(unique=True)),
                ('board', models.TextField(default='["", "", "", "", "", "", "", "", ""]')),
                ('active_player', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('active', 'Activa'), ('won', 'Ganada'), ('tie', 'Empate')], default='active', max_length=6)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
